version: '2'

services:
  app:
    image: willyb321/sharry
    build: .
    env_file: .env
    environment:
      - SHARRY_BIND_HOST=0.0.0.0
      - SHARRY_DB_PASSWORD=sharry
      - SHARRY_BIND_PORT=9090
      - SHARRY_BASE_URL=http://localhost:9090
    networks:
      - sharry
    links:
      - db:db

  web:
    image: nginx
    labels:
      - "traefik.docker.network=sharry"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:files.willb.info"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - sharry

  db:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=sharry
      - POSTGRESQL_DATABASE=sharry
    networks:
      - sharry
    volumes:
      - sharry_db:/bitnami




networks:
  sharry:

volumes:
  sharry_db:
